# Generated by Django 4.1.2 on 2022-10-27 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('postagem_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=500)),
                ('imagem', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
                ('data_criação', models.DateField(auto_now_add=True)),
                ('curtidas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'db_table': 'postagens',
            },
        ),
    ]
