# Generated by Django 4.1.2 on 2022-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postagem",
            old_name="data_criação",
            new_name="data_criacao",
        ),
        migrations.AlterField(
            model_name="postagem",
            name="curtidas",
            field=models.BooleanField(),
        ),
    ]
