# Generated by Django 4.1.2 on 2022-10-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_data_criação_postagem_data_criacao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postagem",
            old_name="curtidas",
            new_name="curtida",
        ),
    ]
