# Generated by Django 4.1.2 on 2022-10-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_curtidas_postagem_curtida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postagem",
            name="curtida",
        ),
        migrations.AddField(
            model_name="postagem",
            name="curtidas",
            field=models.IntegerField(default=0),
        ),
    ]
