# Generated by Django 4.1.2 on 2022-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_postagem_curtida_postagem_curtidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="autor",
            field=models.CharField(default="Fernanda Fernandez", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postagem",
            name="texto",
            field=models.CharField(max_length=1000),
        ),
    ]
