# Generated by Django 4.1.2 on 2022-11-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_postagem_autor_alter_postagem_texto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="texto",
            field=models.CharField(max_length=3000),
        ),
    ]
